name: ci
on: [push, pull_request]
jobs:
    ci:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                name: [ubuntu]
                include:
                    - name: ubuntu
                      os: ubuntu-18.04
                      vcpkg_triplet: x64-linux
        steps:
            - name: Checkout litecoin
              uses: actions/checkout@v2
              with:
                  path: litecoin
                  repository: ltc-mweb/litecoin
            - name: Checkout libmw
              uses: actions/checkout@v2
              with:
                  path: libmw
                  repository: ltc-mweb/libmw
                  submodules: 'recursive'
            - name: Install dependencies
              run: |
                sudo apt-get update --fix-missing
                sudo apt-get install patchelf build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev libdb-dev libdb++-dev libspdlog-dev libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler
            - name: Install gcc 8
              run: |
                echo "Tag Name: ${{ steps.tagName.outputs.tag }}"
                sudo apt install gcc-8 g++-8 libgflags-dev build-essential
                echo "export CC=/usr/bin/gcc-8"
                echo "export CXX=/usr/bin/g++-8"
                sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 8
                sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 8
            - name: Windows build
              run: |
                sudo apt install g++-mingw-w64-x86-64
                sudo update-alternatives --config x86_64-w64-mingw32-g++
                cd litecoin
                cd depends
                make HOST=i686-w64-mingw32
                cd ..
                ./autogen.sh
                CONFIG_SITE=$PWD/depends/i686-w64-mingw32/share/config.site ./configure --prefix=/
                make