name: ci
on: [push, pull_request]
jobs:
    mingw:
        name: Windows (MinGW)
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout litecoin
              uses: actions/checkout@v2
              with:
                  path: litecoin
                  repository: ltc-mweb/litecoin
            - name: Install dependencies
              run: |
                sudo apt-get update --fix-missing
                sudo apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 g++-mingw-w64-x86-64 cmake nsis
            - name: 'Build litecoin'
              working-directory: litecoin
              run: |
                sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
                cd depends
                make HOST=x86_64-w64-mingw32
                cd ..
                ./autogen.sh
                CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
                make -j8
                make deploy
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              env:
                    GITHUB_RUN_ID: ${{ github.run_id }}    
              with:
                    name: litecoin_windows_${{ env.GITHUB_RUN_ID }}
                    path: ${{ github.workspace }}/litecoin/litecoin-0.18.1-win64-setup.exe